#!/bin/bash
INCREMENTIP=/home/jake/bin/incrementip
SSLTEMPLATE=/usr/share/ssl-cert/ssleay.cnf
HOSTNAME=`hostname`

if [ -z $1 ]; then
	echo Usage: $0 DOMAIN
	exit 1
fi
echo Adding $1 ...

# Get a new IP
SITEIP=`awk '/^127.0.1/ {print $1}' /etc/hosts | tail -n1 | xargs $INCREMENTIP`

# Create a temporary config for SSL
TMPCONF=/tmp/ssl.`date +%s`.cnf
sed 's/@HostName@/'$HOSTNAME'.'$1'/' $SSLTEMPLATE > $TMPCONF
PEM=/etc/apache2/ssl/$1.pem

TMPOUT="$(mktemp)"  || exit 1

trap "rm -f $TMPOUT $TMPCONF" EXIT

# Run the root commands
su -c "echo Use SvnHost $1 >> /etc/apache2/sites-enabled/sites; \
echo $SITEIP $HOSTNAME.$1 >> /etc/hosts; \
if ! openssl req -config $TMPCONF -new -x509 -days 3650 -nodes -out $PEM -keyout $PEM > $TMPOUT 2>&1; \
then \
  echo Could not create certificate. Openssl output was: >&2; \
  cat $TMPOUT >&2; \
  exit 1; \
fi; \
chmod 600 $PEM; \
cd $(dirname $PEM); \
ln -sf $(basename $PEM) \$(openssl x509 -hash -noout -in $(basename $PEM)); \
apache2ctl restart"

echo Done.

