#!/usr/bin/php
<?php
$fh = fopen('php://stdin', 'r');

$colors = array(
	'black'        => '\e[30m',
	'red'          => '\e[31m',
	'green'        => '\e[32m',
	'yellow'       => '\e[33m',
	'blue'         => '\e[34m',
	'magenta'      => '\e[35m',
	'cyan'         => '\e[36m',
	'white'        => '\e[37m',
	'black_bold'   => '\e[1;30m',
	'red_bold'     => '\e[1;31m',
	'green_bold'   => '\e[1;32m',
	'yellow_bold'  => '\e[1;33m',
	'blue_bold'    => '\e[1;34m',
	'magenta_bold' => '\e[1;35m',
	'cyan_bold'    => '\e[1;36m',
	'white_bold'   => '\e[1;37m',
	'reset'        => '\e[0m'
);

$color_map = array(
	'red' => 'red',
	'orange' => 'yellow',
	'blue' => 'cyan',
	'green' => 'green'
);

function colorf () {
	global $colors;
	$args = func_get_args();
	$strf = array_shift($args);
	passthru('/bin/echo -e "' . vsprintf($strf, $args) . $colors['reset'] . '"');
}

/*
foreach ($colors as $name => $code) {
	passthru('/bin/echo -e "' . sprintf("%s%s%s", $code, $name, $colors['reset']) . '"');
}
*/

while ($json = fgets($fh)) {
	$package = json_decode($json, true);
	if (json_last_error() != JSON_ERROR_NONE) {
		echo "no clude\n";
		continue;
	}
	$date = new DateTime();
	$date->setTimestamp($package['timestamp'] / 1e9);
	$stamp = '[' . $date->format('His') . ']';
	$indent = str_repeat(' ', strlen($stamp) + 1);

	$server_name = $package['data']['server_name'];
	if ($server_name == 'CLI') {
		$server_name .= ' ';
	}

	colorf("%s%s %s%s",
		$colors['green_bold'],
		$stamp,
		$server_name,
		$package['data']['uri']
	);
	colorf("%s%sTime: %0.4fs Memory: %0.4fM",
		$colors['green'],
		$indent,
		$package['data']['execution_time'],
		$package['data']['memory_usage'] / 1024 / 1024
	);

	if (array_key_exists('messages', $package['data'])) {
		foreach ($package['data']['messages'] as $error) {
			if (!isset($error['file'], $error['level'], $error['line'], $error['color'])) {
				print_custom($error);
			} else {
				print_error($error);
			}
		}
	}
}

function print_error($error) {
	global $colors, $color_map, $indent;
	if (strpos($error['file'], 'httpdocs') !== false) {
		list($junk, $path) = explode('httpdocs', $error['file']);
	} else {
		$path = $error['file'];
	}
	colorf("%s%s%s: %s:%d\n%s    %s",
		$colors[$color_map[$error['color']]],
		$indent,
		$error['level'],
		$path,
		$error['line'],
		$indent,
		$error['message']
	);
}

function print_custom($error) {
	global $colors, $color_map, $indent;
	colorf("%s%sCustom Message: KEY              VALUE",
		$colors['magenta_bold'],
		$indent
	);
	foreach ($error as $k => $v) {
		colorf("%s%s%s%-16s %s",
			$colors['magenta_bold'],
			$indent,
			str_repeat(' ', strlen("Custom Message: ")),
			$k,
			$v
		);
	}
}
