#!/bin/sh
if [ -z $1 ]; then
	echo "USAGE: $0 server [revision]"
	exit 1
fi

SERVER=$1
REVISION=$2

FETCH_REVISION="svn info public_html | grep Revision | sed 's/Revision: //'"

PREVIOUS_REVISION=`ssh ${SERVER} "${FETCH_REVISION}"`

if [ -z $2 ]; then
	COMMAND="svn up public_html"
else
	COMMAND="svn up -r ${REVISION} public_html"
fi

ssh ${SERVER} "${COMMAND}"

CURRENT_REVISION=`ssh ${SERVER} "${FETCH_REVISION}"`

echo "Previous Revision: $PREVIOUS_REVISION"
echo "Current Revision:  $CURRENT_REVISION"

echo "http://traffic.okco.com/update-notify.php?user=`whoami`&server=${SERVER}&previous=${PREVIOUS_REVISION}&current=${CURRENT_REVISION}"
